# Generated by Django 5.2.10 on 2026-02-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='community_c_post_id_f91575_idx',
            old_name='community_c_post_id_4e4052_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='community_c_post_id_bea033_idx',
            old_name='community_c_post_id_3fdc34_idx',
        ),
        migrations.RenameIndex(
            model_name='karmaactivity',
            new_name='community_k_created_b875aa_idx',
            old_name='community_k_created__8d2ab6_idx',
        ),
        migrations.RenameIndex(
            model_name='karmaactivity',
            new_name='community_k_user_id_6fc80f_idx',
            old_name='community_k_user_id_23b4e1_idx',
        ),
    ]
